version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16  # Use a Node.js version compatible with your dependencies
    commands:
      - npm install -g npm@7  # Update npm to a more recent version
      - npm install  # Install Node.js dependencies

  build:
    commands:
      - npm run build  # Build the React app

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - 'node_modules/**/*'
